name: Continuous Live Stream to Facebook

on:
  workflow_dispatch:  # لتشغيل العمل يدويًا من GitHub
  schedule:
    - cron: "*/10 * * * *"  # لتشغيل العمل كل 10 دقائق

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Continuous Streaming
      run: |
        while true; do
          ffmpeg -re -i "http://het126a.4rouwanda-shop.store/live/9787488847/index.m3u8?t=K7g_eFtVSsa3oCEl_FSXug&e=1731112568" \
          -c:v copy -c:a aac -strict -2 -f flv \
          rtmps://live-api-s.facebook.com:443/rtmp/FB-122163733676260989-0-Abyg21LTB_nbdOCJ \
          -fflags nobuffer
          echo "Stream ended. Restarting..."  # طباعة رسالة إذا انتهى البث
          sleep 5  # الانتظار لمدة 5 ثوانٍ قبل المحاولة مرة أخرى
        done

    - name: Check Stream Status
      run: |
        sleep 600  # الانتظار لمدة 10 دقائق لمراقبة البث
